env:
  expert_policy_file: ../../../hw1/roble/policies/experts/Ant.pkl
  expert_data: ../../../hw1/roble/expert_data/expert_data_Ant-v2.pkl
  exp_name: bob
  env_name: Ant-v2
  max_episode_length: 1000
  render: true
alg:
  num_rollouts: 5
  do_dagger: true
  num_agent_train_steps_per_iter: 1000
  n_iter: 21
  batch_size: 1000
  eval_batch_size: 10000
  train_batch_size: 1024
  n_layers: 2
  network_width: 64
  learning_rate: 0.005
  max_replay_buffer_size: 1000000
  use_gpu: false
  which_gpu: 0
  discrete: false
  ac_dim: 0
  ob_dim: 0

logging:
  video_log_freq: 5
  scalar_log_freq: 1
  save_params: true
  random_seed: 1234
